server:
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  data:
    mongodb:
#      ??
      uri: "mongodb://root:root@localhost:8085/"
      database: pdf-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
