server:
#  more ?
  port: 8080

spring:
  data:
    mongodb:
#      ??
      uri: "mongodb://root:root@db:27017/"
#     rename
      database: example-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
