server:
  error:
    whitelabel:
      enabled: true
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:8085/"
      database: pdf-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: postgres
    password: postgres

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 780110692711-ssf04377tlbsqo12728g4fiumndsplpg.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 3480580642161692
            clientSecret: d2f52103fb154e5cf77e706c2ad35594
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 10800000
  cors:
    allowedOrigins: http://localhost:4200
  oauth2:
    authorizedRedirectUri: http://localhost:4200/oauth2/redirect
